#place(top, dy: -1000pt)[
  = Anglické písničky
]

#include "aberdeen.typ"
#include "all_my_loving.typ"
#include "blue.typ"
#include "eeeaaaooo.typ"
#include "got_my_mind_set_on_you.typ"
#include "hallelujah.typ"
#include "ill_be_there_for_you.typ"
#include "leaving_on_a_jet_plane.typ"
#include "lemon_tree.typ"
#include "let_it_be.typ"
#include "make_your_own_kind_of_music.typ"
#include "mr_tambourine_man.typ"
#include "no_milk_today.typ"
#include "program_in_c.typ"
#include "red_dwarf_theme.typ"
#include "riptide.typ"
#include "rolling_in_the_deep.typ"
#include "scarborough_fair.typ"
#include "someone_like_you.typ"
#include "the_sound_of_silence.typ"
#include "undisclosed_desires.typ"
#include "viva_la_vida.typ"
#include "we_didnt_start_the_fire.typ"
#include "yesterday.typ"
#include "zephyr_song.typ"
